name: "Onedrive Backup"
version: "0.1"
slug: hassio_onedrive_backup
description: >-
  "Automatic backups from Home Assistant to Onedrive"
arch:
  - amd64
  - armv7
  - aarch64
  - amd64
  - i386
url: "https://github.com/lavinir/hassio-onedrive-backup"
map:
  - config
  - ssl
  - backup:rw
options:
  local_backup_num_to_keep : 2
  onedrive_backup_num_to_keep : 2
  backup_interval_days : 3
schema:
  local_backup_num_to_keep : "int(0,)"
  onedrive_backup_num_to_keep : "int(1,)"
  backup_interval_days : "float(0,)"
  backup_passwd : "password?"
hassio_role : "backup"
hassio_api : true
image: repo/{arch}-my-custom-addon